### ISSUE TITLE
Focus area proposal: Organizations can be divided into foundations and commercial companies

### ISSUE THREAD

**Issue by king-gao** [chaoss/wg-value#82] opened 2020-04-23 16:56 UTC
### **What value can open source bring to commercial companies:**
1. **Help the company build a good Brand in the world:** the company is willing to succeed with other partners, prosper the ecology, and achieve a win-win situation. It can be seen that in the past few years, the top technology companies in the world brand ranking have increasingly embraced the trend of open source.
2. **Reduce the cost of staff selection for enterprises:** Now more and more companies are recruiting people who prefer to contribute to the community. If the contributors have updated the applicant company, it will be better and the code style and How the company communicates with people in the project，ect.
3.**Reduce the development cost of an enterprise, and it can be technically complementary to other enterprises:** there is a competitive relationship between different enterprises, and the foundation provides a collaborative platform, regardless of whether the company is competition or cooperation, different enterprises can work together to complete a Projects are used for their own products.
4. **Control the development of the community to meet the strategic needs of the company:** For the company, it is hoped that the open source project will be developed in accordance with the company's strategic line, more people will contribute to the community, and have more influence in the community, which can affect the community Future technical routes and decisions.
### **On the other hand, the value to the foundation:**
1.  A good open source project joining the foundation will enhance the foundation's brand value, which is the same as the enterprise. The major foundations are willing to accept good open source projects, and are willing to support the project, or even incubate, to help the project succeed. Around this project will also spawn more supporting facilities, such as the Linux supporting tools under the Linux Foundation, which will attract more and more developers to invest in, and the Foundation will also provide them with good help to prosper together. Foundations, foundations can get better donations from various companies, and more volunteers, because everyone can improve their capabilities in the foundation.
2. The foundation is a non-profit organization, which is different from enterprises.Enterprises goal is
make more money. For the foundation, it is because of the foundation's management and ownership of software intellectual property rights that the project has become a neutral place and collaboration between enterprises has become possible.

**Comment by LawrenceHecht** [comment] 2020-04-24 20:21
It is easiest to just focus on the value to a commercial enterprise.

If you want to look at the value of foundations, the measures related to effectiveness of governance, training, and recruitment would be most important.

**Comment by mbbroberg** [comment] 2020-05-07 14:25
@king-gao thank you for sharing your proposal. I'm not convinced the value between corporation and foundation are mutually exclusive, and therefore won't be easy to separate categorically. 

For example, under foundation, both topics are relevant to the enterprise: 

1. A company may want to "adopt" an open source project for all the reasons you list 
2. A foundation, while nonprofit by design, works under the same financial constraints of a corporation. To say it another way, they depend on funding, and therefore have to make tough decisions on when to fund community and when to stop investment. 

Instead of thinking of these as separate focus groups, I would encourage us all to not worry ourselves with focus groups, which are optional, and to prioritize **getting metrics that represent value into this organization.** 

Everything you listed is a form of value -- brand awareness, reduced cost for recruitment, reduce development costs, control. If you agree, I believe the next step is to take a look at the overall metrics of CHAOSS, assess if any of these are covered elsewhere, then propose metrics that fill gaps.

**Comment by king-gao** [comment] 2020-05-07 14:43
hi Mbbroberg,thank you for response. yes, I agree with you,when I open this issue,I realize that it may be difficult to distinguish between foundations and companies.
But I can't find a WG in chaoss can cover this metrics,maybe we can transfer this issue to common WG?

**Comment by LawrenceHecht** [comment] 2020-05-07 14:53
I talked about this yesterday in a discussion in this working group: https://discourse.sustainoss.org/c/working-groups/accountability-transparency/. Once they move farther along, they expect to look at value too, and will reach out to CHAOSS then.

**Comment by mbbroberg** [comment] 2020-05-07 16:03
>  But I can't find a WG in chaoss can cover this metrics,maybe we can transfer this issue to common WG?

My take is that the working groups aren't quite right. @king-gao I believe this is absolutely the right working group for financial cost consideration. Please propose these metrics using the process [outlined here](https://github.com/chaoss/wg-value#propose-a-metric) - we'd love to have them!

**Comment by germonprez** [comment] 2020-05-07 16:49
Thanks everyone for this discussion. A few thoughts. 

Often times, we capture the context (foundation vs. company) in the Objectives part of a metric. It is in this heading where we give examples of how a metric could be useful in practice. I'd suggest that we consider this distinction for nearly every metric in the Value WG. 

@king-gao It seems that what you are proposing is really a metric for each: 

1) Branding 
2) Staff Costs
3) Development Costs
4) Control 

I believe that these could be distinct on their own.

**Comment by mbbroberg** [comment] 2020-06-18 15:40
Closing this in favor of #93

**Closed by mbbroberg** 2020-06-18 15:40 UTC
