### ISSUE TITLE
release changes for copy editing and standardization

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#41] opened 2019-08-02 18:47 UTC
general changes -

removed numbers from headers

moved formulas into description

merged examples with known implementations

**Comment by GeorgLink** [comment] 2019-08-02 18:55
Are these things that need to get done or are you informing us of these changes? Sorry, the issue is not clear to me.

**Comment by klumb** [comment] 2019-08-02 18:58
Sorry, these are changes that were made. 

I created the issue for transparency purposes.

**Comment by GeorgLink** [comment] 2019-08-02 19:03
Thank you for the clarity.
How about using pull requests to not only document the change, but also
link it to the specific commit?
Or, providing a link to the commit in this issue?

After we add more work, it may otherwise be difficult to connect the change
made (commit) with this message or description of the change.

**Comment by klumb** [comment] 2019-08-02 19:10
Yes, that is certainly best practice. Because these were primarily just copy-edits for the full release and there are time constriants, we pushed them direct to all of the wg repositories. 

In the future we will use best practices.

**Comment by andyl** [comment] 2019-08-02 20:19
Thanks for posting Kevin.  Is it OK to close this issue now?

**Comment by klumb** [comment] 2019-08-02 20:21
Yes, we can close it.

**Closed** 2019-08-02 20:22 UTC

**Comment by GeorgLink** [comment] 2019-08-02 22:28
I have no issues with you doing time sensitive work and merging your own
pull requests -- I know I have in the past. :D
